---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we contact you?
      placeholder: example@example.com
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue.
      placeholder: Add details here.
      

