---
name: Contacts
description: File a bug report
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide the following details to help us understand the issue.

  - type: input
    id: contact_details
    attributes:
      label: Contact Details
      description: How can we contact you if we need more information?
      placeholder: ex. email@example.com

  - type: dropdown
    id: type_of_request
    attributes:
      label: Type of Request
      description: Select the type of request you are making.
      options:
        - New Feature
        - Bug Report
        - Enhancement

  - type: dropdown
    id: os_suggestion
    attributes:
      label: Operating System
      description: What operating system is this related to?
      options:
        - Windows
        - macOS
        - Linux
        - Other

  - type: textarea
    id: details
    attributes:
      label: Details of Your Suggestion or Bug
      description: Provide a clear and detailed explanation of your request or issue.
      placeholder: Explain what you want or describe the problem in detail.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please include any relevant log output to help us diagnose the issue.
      placeholder: Paste logs here.

  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct Agreement
      description: By submitting this issue, you agree to follow the [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
